var MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/smallgame_get";

MongoClient.connect(url, function(err, db) {
  if (err) throw err;
  var quiz = [
    { ques: '中央大學位在哪個縣市?', options: ['桃園市','竹北市','嘉義市','台中市'] , correctIndex:0},
    { ques: '中央大學的簡稱為?', options: ['央大','中央','中大','以上皆非'] , correctIndex:2},
    { ques: '如果想要搭公車到市區應搭幾號?', options: ['1920','132','9025','321'] , correctIndex:1},
    { ques: '如果想要搭公車直達台北應搭幾號?', options: ['132','1920','9025','133'] , correctIndex:2},
    { ques: '現任校長的名子?', options: ['蔣偉寧','周景揚','蔣中正','李四光'] , correctIndex:1},
    { ques: '冷氣卡應到哪的全家買?', options: ['男9的和女14的','松苑的和男9的','松苑的和女14的','以上皆是'] , correctIndex:0},
    { ques: '到管院的路上有一條路叫甚麼川?', options: ['百花川','長谷川','青木川','都不川'] , correctIndex:0},
    { ques: '藝文中心在哪?', options: ['遊藝館','依仁堂','電算中心','舊圖'] , correctIndex:3},
    { ques: '松果餐廳在男幾下面?', options: ['男9','男11','男13','男7'] , correctIndex:3},
    { ques: '照顧流浪犬的社團為?', options: ['中大愛狗社','中大汪汪社','中大狗狗社','以上皆非'] , correctIndex:1},
    { ques: '何者為大一必修課程?', options: ['日文','法文','國文','西班牙文'] , correctIndex:2},
    { ques: '132公車單程票價為何?', options: ['15','17','18','19'] , correctIndex:2},
    { ques: '公用腳踏車叫甚麼?', options: ['小白','小黑','小黃','小綠'] , correctIndex:3},
    { ques: '大一必修體育佔幾學分?', options: ['0','2','3','1'] , correctIndex:0},
    { ques: '請問中央大學沒有開設哪一堂語文課？', options: ['西班牙文','俄文','法文','德文'] , correctIndex:1},
    { ques: '請問中央大學有開設哪一堂語文課？', options: ['德文','俄文','義大利文','馬來文 '] , correctIndex:0},
    { ques: '中央大學哪一項運動沒有設置室內場館？', options: ['排球','籃球','桌球','網球'] , correctIndex:3},
    { ques: '中央大學的專業實驗劇場-黑盒子，隸屬於哪個單位？', options: ['資電學院','文學院','管理學院','工學院'] , correctIndex:1},
    { ques: '中央可以固定一段時間會有電影放映的地方在哪裡?', options: ['107電影院','108電影院','106電影院','105電影院'] , correctIndex:0},
    { ques: '若持中大證件到校內的小木屋鬆餅點餐，一項可折多少？', options: ['10','7','5','9'] , correctIndex:3},
    { ques: '操場跑道的顏色為何?', options: ['藍色','紅色','黃色','白色'] , correctIndex:0},
    { ques: '女生宿舍最貴的為哪棟?', options: ['女4','女14','女1','女4'] , correctIndex:1},
    { ques: '中央大學的地址?', options: ['中央路300號','學央路300號','中大路300號','以上皆非'] , correctIndex:2},
    { ques: '幾號公車可以直達桃園高鐵站?', options: ['133','154','178','172'] , correctIndex:3},
    { ques: '小木屋後面是甚麼學院?', options: ['管學院','文學院','理學院','工學院'] , correctIndex:0},
    { ques: '學校有雕塑大師朱銘的作品嗎?', options: ['沒有','有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '男九前面的噴水池是叫?', options: ['鯉魚池','蓮花池','烏龜池','洗澡池'] , correctIndex:2},
    { ques: 'K書中心在哪?', options: ['國鼎大樓','行政大樓','管理二館','舊圖'] , correctIndex:3},
    { ques: '非游泳課時間去游泳要付?', options: ['30','40','50','60'] , correctIndex:0},
    { ques: '非羽球課時間去打羽球要付?', options: ['30','40','50','60'] , correctIndex:0},
    { ques: '學校主要的校風為?', options: ['積極','純樸','活潑','朝氣'] , correctIndex:1},
    { ques: '學校有醫學院嗎?', options: ['有','以前有','沒有','以上皆是'] , correctIndex:2},
    { ques: '本校隸屬哪個系統?', options: ['台大聯盟','中聯大','央聯大','台聯大'] , correctIndex:3},
    { ques: '搭台聯大的專車去清大要錢嗎?', options: ['要','不要','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '搭台聯大的專車去交大要錢嗎? ', options: ['不要','要','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '搭台聯大的專車去陽明要錢嗎? ', options: ['要','不要','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '中大在復校前所在位置為? ', options: ['山東','陝西','南京','遼北'] , correctIndex:2},
    { ques: '凌晨3點有開的早餐店為?', options: ['萊姆思','達啵廚房','歐姆萊斯','惟客'] , correctIndex:3},
    { ques: '校內有7-11嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '中央大學郵局在?', options: ['男9旁','男7旁','女4旁','女14旁'] , correctIndex:3},
    { ques: '想買二手教科書可到?', options: ['敦煌書局','全家超商','7-11','OK便利超商'] , correctIndex:0},
    { ques: '學校哪買的到床墊? ', options: ['全家超商','581生活館','7-11','OK便利超商'] , correctIndex:2},
    { ques: '選課要上哪個網站?', options: ['portal','lms','中央資管','中央資工'] , correctIndex:0},
    { ques: '學校約有幾個姊妹校?', options: ['70','80','100','170'] , correctIndex:3},
    { ques: '一張冷氣卡裡面有多少錢?', options: ['250','500','150','200'] , correctIndex:1},
    { ques: '學校哪裏有ubike?', options: ['觀景台旁','中大門口','總圖書館前','小木屋旁'] , correctIndex:2},
    { ques: 'Ubike前幾分鐘不用錢?', options: ['30','60','90','120'] , correctIndex:0},
    { ques: '我們可持中大圖書證到清大借書嗎?', options: ['可','不可','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '我們可持中大圖書證到交大借書嗎?', options: ['不可','可','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '我們可持中大圖書證到陽明借書嗎?', options: ['可','不可','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '圖書館平日幾點開館?', options: ['8am','9am','10am','11am'] , correctIndex:0},
    { ques: '圖書館假日幾點開館?', options: ['9am','8am','10am','11am'] , correctIndex:3},
    { ques: '圖書館平日幾點閉館?', options: ['9:30pm','10pm','11pm','12pm'] , correctIndex:0},
    { ques: '圖書館假日幾點閉館?', options: ['6pm','7pm','9pm','10pm'] , correctIndex:1},
    { ques: '圖書館書最多可以借幾本?', options: ['5','6','10','20'] , correctIndex:3},
    { ques: '校內工讀哪個網站可以找到?', options: ['lms','中央資管網頁','portal','中央資工網頁'] , correctIndex:2},
    { ques: '通識課程在畢業前應修滿幾學分?', options: ['18','20','15','14'] , correctIndex:3},
    { ques: '全校有幾個學系?', options: ['22','33','44','55'] , correctIndex:0},
    { ques: '學生專用信箱web mail是由哪個單位負責管理的？', options: ['圖書館','電子計算中心','教務處','學務處'] , correctIndex:1},
    { ques: '中央大學語言中心位在哪一棟大樓？', options: ['志希館','地科院','綜教館','管理二館'] , correctIndex:2},
    { ques: '中央大學宿舍網路校外的上傳流量『加總』之後上限為?', options: ['沒限制','3GB','4GB','5GB'] , correctIndex:1},
    { ques: '中央大學宿舍網路校外的下載流量『加總』之後上限為?', options: ['沒限制','3GB','4GB','5GB'] , correctIndex:0},
    { ques: '如果腳踏車壞了要去哪修?', options: ['找警衛伯伯','全家','家樂福','後門腳踏車店'] , correctIndex:3},
    { ques: '中央大學的英文縮寫為?', options: ['NCU','HGSH','CYGSH','CYSH'] , correctIndex:0},
    { ques: '郵局平日營業時間為?', options: ['9:30~18:00','8:00~17:00','10:00~17:00','9:00~18:00'] , correctIndex:1},
    { ques: '若有人寄信給你,你該到行政大樓的哪領?', options: ['出納組','課務組','文書組','生活輔導組'] , correctIndex:2},
    { ques: '若想網購,後門的7-11叫甚麼門市?', options: ['學店門市','中央門市','中大門市','學央門市'] , correctIndex:3},
    { ques: '國鼎圖書館是為了紀念哪位校友?', options: ['李國鼎','吳健雄','陳鼎圖','王圖書'] , correctIndex:0},
    { ques: '中央大學的校樹為?', options: ['竹','松','梅','荷'] , correctIndex:1},
    { ques: '下列哪個偶像劇有在中央取景?', options: ['1989一念間','極品絕配','我的自由年代','我的愛情不平凡'] , correctIndex:2},
    { ques: '校內沒有何種運動場地?', options: ['重訓室','壘球場','籃球場','保齡球館'] , correctIndex:3},
    { ques: '校內沒有何種運動場地?', options: ['高爾夫球場','排球場','壘球場','籃球場'] , correctIndex:0},
    { ques: '校內有何種運動場地?', options: ['高爾夫球場','重訓室','足球場','保齡球館'] , correctIndex:1},
    { ques: '下列何者為中央大學的體育館名字?', options: ['據德樓','游藝館','依仁堂','志道樓'] , correctIndex:2},
    { ques: '校內有個著名的劇場叫?', options: ['名劇場','107電影院','中央劇場','黑盒子劇場'] , correctIndex:3},
    { ques: '若遇到人生低潮該去哪尋求協助?', options: ['諮商中心','校長室','教務處','學務處'] , correctIndex:0},
    { ques: '排球場在哪?', options: ['中大湖旁','依仁堂旁','舊圖旁','總圖書館旁'] , correctIndex:1},
    { ques: '你現在念哪所大學?', options: ['中山','中興','中央','中正'] , correctIndex:2},
    { ques: '中央的垃圾場在?', options: ['中大湖後面','文院旁邊','籃球場旁','男9後面'] , correctIndex:3},
    { ques: '中央大學除了哪兩天以外都有垃圾車時間?', options: ['六日','一二','日一','五六'] , correctIndex:0},
    { ques: '凌晨想吃消夜可到哪吃?', options: ['後門','宵夜街','女宿','男宿'] , correctIndex:1},
    { ques: '中央最新成立的學院為?', options: ['理學院','管理學院','生醫理工學院','資電學院'] , correctIndex:2},
    { ques: '中央大學專屬的電台為?', options: ['大中大電視台','中中大電視台','好中大電視台','小中大電視台'] , correctIndex:3},
    { ques: '中央學生自己專屬的學校信箱結尾為何?', options: ['@cc.ncu.edu.tw','@cc.ntu.edu.tw','@cc.cygsh.edu.tw','@cc.cysh.edu.tw'] , correctIndex:0},
    { ques: '期中期末考時k書中心會開多久?', options: ['22點關','23點關','21點關','24小時開放'] , correctIndex:3},
    { ques: '平時k書中心會開多久?', options: ['24小時開放','23點關','22點關','21點關'] , correctIndex:1},
    { ques: '請問106學年度，中央大學的FB社團名稱為何?', options: ['2016 嶄．望','中央大學','2017邂逅中央','中大自由年代'] , correctIndex:2},
    { ques: '中央甚麼樹最多?', options: ['榕樹','松樹','芒果樹','西瓜樹'] , correctIndex:1},
    { ques: '中央目前有幾個學院?', options: ['8','10','12','14'] , correctIndex:0},
    { ques: '請問中央大學的校色為什麼顏色?', options: ['紅綠','藍紫','紫金','靛紅'] , correctIndex:2},
    { ques: '中央大學內有幾家全家?', options: ['3','5','7','9'] , correctIndex:0},
    { ques: '中央大學內最高建築為哪棟?', options: ['客家學院','管理二館','舊圖','女14'] , correctIndex:3},
    { ques: '中央大學內的新圖書館(總圖書館)總共有幾層樓?', options: ['8','9','10','11'] , correctIndex:0},
    { ques: '你即將進入的國立中央大學於今年滿幾週年呢?', options: ['101','102','99','98'] , correctIndex:1},
    { ques: '校內的腳踏車打氣站分別位於何處?', options: ['小木屋旁','舊圖旁','正門警衛室','總圖書館旁'] , correctIndex:2},
    { ques: '學生機車騎入校園之入校時間限制時間為?', options: ['12~18時','11~23時','10~23時','8~21時'] , correctIndex:3},
    { ques: '宿舍網路啟動碼價錢要花多少錢?', options: ['800','1500','1000','1200'] , correctIndex:0},
    { ques: '請問中央大學道路的最高限速是多少公里?', options: ['5','10','15','25'] , correctIndex:3},
    { ques: '宿舍網路卡需要到行政大樓中的哪個處室買?', options: ['文書組','出納組','註冊組','課務組'] , correctIndex:1},
    { ques: '哪個宿舍有桌球室?', options: ['女2','女4','男9','女1'] , correctIndex:2},
    { ques: '若要申請寒假宿舍要到哪申請?', options: ['系辦','行政大樓','女宿傳達室','宿舍服務中心'] , correctIndex:3},
    { ques: '宿舍門禁為?', options: ['12pm','沒門禁','11pm','10pm'] , correctIndex:1},
    { ques: '哪間宿舍地下室有餐廳、581商店、全家、影印店等等?', options: ['女1','女14','男9','男7'] , correctIndex:1},
    { ques: '知名作家吳明益畢業於中央哪個科系?', options: ['地科系','資管系','中文系','客家系'] , correctIndex:2},
    { ques: '知名女演員張鈞甯畢業於中央哪個研究所?', options: ['客研所碩士','資管所碩士','EMBA 碩士','產經所碩士'] , correctIndex:3},
    { ques: '知名男演員王宥勝畢業於中央哪個科系?', options: ['財經系','中文系','大氣系','資工系'] , correctIndex:0},
    { ques: '知名藝人浩角翔起的浩子畢業於中央哪個科系?', options: ['電機系','資管系','化材系','資工系'] , correctIndex:1},
    { ques: '校歌中 ”宏我黌舍兮”的”黌”字讀做?', options: ['ㄩˋ','ㄏㄨㄤˊ','ㄏㄨㄥˊ','ㄏㄠˋ'] , correctIndex:2},
    { ques: '中央大學沒有甚麼友會?', options: ['雲嘉會','中友會','僑友會','北友會'] , correctIndex:3},
    { ques: '如果不會用宿網可以去哪個網站查詢?', options: ['中央電子計算中心','lms','服務學習網','生活職涯網'] , correctIndex:0},
    { ques: '中央哪個網站有提供Microsoft Office的下載服務?', options: ['portal','中央電子計算中心','服務學習網','lms'] , correctIndex:1},
    { ques: '中央哪個網站有提供防毒軟體的下載服務?', options: ['portal','服務學習網','中央電子計算中心','生活職涯網'] , correctIndex:2},
    { ques: '科學四館又名甚麼?', options: ['國鼎大樓','依仁堂','游藝館','健雄館'] , correctIndex:3},
    { ques: '健雄館是為了紀念誰?', options: ['吳健雄','宋健雄','王健雄','黃健雄'] , correctIndex:0},
    { ques: '位於阿里山海拔2862m的鹿林天文台由本校哪個所所管理?', options: ['地質所','天文所','生醫所','資管所'] , correctIndex:1},
    { ques: '學校哪裡有天文台?', options: ['理學院','管院','科學四館','工學院'] , correctIndex:2},
    { ques: '小木屋鬆餅的鬆餅有賣冰淇淋口味的鬆餅嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '小木屋鬆餅有賣飲料嗎?', options: ['沒有','有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '女14樓下的全家有自動提款機嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: 'Fb有個社團可以提供中央的學生買賣不要的東西,該社團叫?', options: ['中央省錢站','中央買賣站','中央復活福利社','中央有錢站'] , correctIndex:2},
    { ques: '中央交流選課資訊的fb社團叫?', options: ['中大選課讚讚讚','中央選課必看啦','中大選課快來看','中大選課~Ctrl+F很EAZY!!!',] , correctIndex:3},
    { ques: '中央有設英文畢業門檻嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '中央有設中文畢業門檻嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '中央有設數學畢業門檻嗎?', options: ['有','沒有','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '每個學院的畢業英文畢業門檻相同嗎?', options: ['不同','相同','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '你現在正在使用的網站是由本校哪個團隊所架的?', options: ['新生資訊網','新生滋訊網','新生知訊網','新生姿訊網'] , correctIndex:2},
    { ques: '學校後門那間很優的咖啡甜點店叫?', options: ['Sidewalk','NO.17 White House','迷路','Backdoor Café'] , correctIndex:3},
    { ques: '學校後門那間素食餐廳叫?', options: ['Sidewalk','Backdoor Café','NO.17 White House','迷路'] , correctIndex:0},
    { ques: '如果想吃手工冰淇淋可以到哪家店?', options: ['好兇蛋餅','Sidewalk','Backdoor Café','NO.17 White House'] , correctIndex:1},
    { ques: '夏天時走百花川時有什麼會從樹上掉下來?', options: ['錢','黃金','毛毛蟲','魚'] , correctIndex:2},
    { ques: '大一週會要去哪聽?', options: ['鴻經管','游藝館','管理二館','大講堂'] , correctIndex:3},
    { ques: '大一學生必須聽幾次大一週會?', options: ['4次','3次','2次','1次'] , correctIndex:0},
    { ques: '大一學生必須聽幾次各院院週會?', options: ['1次','2次','3次','4次'] , correctIndex:1},
    { ques: '大一週會要去哪個網站報名?', options: ['生活職涯網','portal','服務學習網','lms'] , correctIndex:2},
    { ques: '學校最多的超商是哪家?', options: ['7-11','OK','萊爾富','全家'] , correctIndex:3},
    { ques: '學校的運動會為期幾天?', options: ['1天','2天','3天','4天'] , correctIndex:1},
    { ques: '若受傷了該去哪處理?', options: ['生活服務組','生活輔導組','衛生保健組','出納組'] , correctIndex:2},
    { ques: '職涯發展中心位在舊圖幾樓?', options: ['2樓','3樓','4樓','5樓'] , correctIndex:0},
    { ques: 'K書中心位在舊圖幾樓?', options: ['2樓','3樓','4樓','5樓'] , correctIndex:0},
    { ques: '找不到人聊心事的你可以前往?', options: ['校長室','行政大樓','警衛室','諮商輔導中心'] , correctIndex:3},
    { ques: '大一新生心理適應座談會辦在幾月?', options: ['9月','10月','11月','12月'] , correctIndex:0},
    { ques: '研究生新生座談辦在幾月?', options: ['9月','10月','11月','12月'] , correctIndex:0},
    { ques: '宿舍中使用一次洗衣機須投多少錢?', options: ['30元','40元','10元','20元'] , correctIndex:2},
    { ques: '宿舍中使用烘衣機30分鐘須投多少錢?', options: ['40元','10元','20元','30元'] , correctIndex:1},
    { ques: '宿舍中使用烘衣機一次最多可以投入幾元?', options: ['20元','30元','40元','50元'] , correctIndex:1},
    { ques: '宿舍中使用脫水機需投多少錢?', options: ['10元','20元','30元','免錢'] , correctIndex:3},
    { ques: '如果想要出國交換可以到哪詢問?', options: ['職涯發展中心','衛生保健組','國際事務處','生活服務組'] , correctIndex:2},
    { ques: '全校路跑男生需跑幾公里?', options: ['4km','5km','9km','10km'] , correctIndex:1},
    { ques: '全校路跑女生需跑幾公里?', options: ['4km','6km','8km','9km'] , correctIndex:0},
    { ques: '中央2006發現的小行星於2016通過審查命名為?', options: ['中央','屏中','中屏','屏東',] , correctIndex:3},
    { ques: '遊藝館的由來出自於下列哪句話?', options: ['不遠遊，遊必有藝','依於仁，遊於藝','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '志道樓的由來出自於下列哪裡?', options: ['孟子','中庸','論語','大學'] , correctIndex:2},
    { ques: '據德樓的由來出自於下列哪裡?', options: ['孟子','中庸','大學','論語'] , correctIndex:3},
    { ques: '依仁堂的由來出自於下列哪裡?', options: ['論語','孟子','中庸','大學'] , correctIndex:0},
    { ques: '目前中央大學校長是誰?', options: ['周璟揚','周景揚','周景陽','周景翔'] , correctIndex:1},
    { ques: '曾經有人掉進百花川嗎?', options: ['有','沒有','目前沒有','真的沒有'] , correctIndex:0},
    { ques: '中央被二一幾次就會被退學?', options: ['2次','3次','4次','5次'] , correctIndex:0},
    { ques: '平常在校內可以騎機車嗎?', options: ['可以','可以吧','應該可以','不行'] , correctIndex:3},
    { ques: '校內公用腳踏車可以騎出校外嗎?', options: ['可以','不行','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '好兇蛋餅晚上幾點開?', options: ['7pm','6pm','5pm','10pm'] , correctIndex:3},
    { ques: '好兇蛋餅幾點關門?', options: ['7am','8am','12am','5am'] , correctIndex:2},
    { ques: '好兇蛋餅從幾點開到幾點?', options: ['10pm~12am','7pm~7am','6pm~8am','5pm~5am'] , correctIndex:0},
    { ques: '你喜歡這個網站嗎?', options: ['不喜歡','很喜歡','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '你喜歡這款遊戲嗎?', options: ['很喜歡','不喜歡','太喜歡了','可愛'] , correctIndex:2},
    { ques: '要輸入網路卡號碼需要至哪個網頁?', options: ['服務學習網','生活職涯網','中央大學學生宿舍網路系統','lms'] , correctIndex:2},
    { ques: '學生宿網系統的使用者專區內之「繳費」地點最常用的方式為?', options: ['直接至行政大樓出納組購買','ATM 繳款','超商繳款','第一銀行臨櫃繳款'] , correctIndex:0},
    { ques: '英語自學中心在哪裡?', options: ['總圖','管理學院','理學院','舊圖'] , correctIndex:3},
    { ques: '英語自學中心觀看英文影片幾分鐘一個戳章?', options: ['40分鐘','50分鐘','30分鐘','20分鐘'] , correctIndex:1},
    { ques: '校內公用腳踏車，俗稱「小綠」，可以私自上鎖嗎?', options: ['不行','可以','以上皆是','以上皆非'] , correctIndex:0},
    { ques: '宿舍網路啟動碼生效時間是「宿網系統註冊完畢後」多久生效?', options: ['註冊馬上生效','須等一段時間','以上皆是','以上皆非'] , correctIndex:1},
    { ques: '宿舍網路每筆的註冊資料, 允許更換 MAC Address(網路啟動碼)幾次?', options: ['1次','2次','3次','5次'] , correctIndex:2},
    { ques: '宿舍網路如果搬到其他宿舍或寢室, 可以修改幾次?', options: ['2次','4次','3次','5次'] , correctIndex:0},
    { ques: '106學年度服務學習總共需要幾個小時才能畢業?', options: ['90小時','100小時','80小時','70小時'] , correctIndex:1},
    { ques: '106學年度服務學習其中藝文時數占多少小時?', options: ['20小時','30小時','40小時','50小時'] , correctIndex:0},
    { ques: '與中央大學服務學習相關資訊需去哪個網站查看?', options: ['lms','portal','國際事務處','中央大學服務學習網'] , correctIndex:3},
  ];

  db.createCollection("quizlist", function(err, res) {
    if (err) throw err;
    console.log("Table created!");
  });
  
  db.collection("quizlist").insertMany(quiz, function(err, res) {
    if (err) throw err;
    console.log("Number of records inserted: " + res.insertedCount);
    db.close();
  });

});




